package thosttraderapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\u02b1\ufffd\ufffd\ufffd\u0377<br>
 * <i>native declaration : ctpapi/linux/ThostFtdcUserApiStruct.h:129</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("thosttraderapi") 
public class CThostFtdcTransferHeaderField extends StructObject {
	/**
	 * \ufffd\u6c7e\ufffd\u0163\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd1.0<br>
	 * C type : TThostFtdcVersionType
	 */
	@Array({4}) 
	@Field(0) 
	public Pointer<Byte > Version() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\u05f4\ufffd\ufffd\ub8ec\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcTradeCodeType
	 */
	@Array({7}) 
	@Field(1) 
	public Pointer<Byte > TradeCode() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06a3\ufffd\ufffd\ufffd\ufffd\ue8ec\ufffd\ufffd\u02bd\ufffd\ufffdyyyymmdd<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({9}) 
	@Field(2) 
	public Pointer<Byte > TradeDate() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\u48ec\ufffd\ufffd\ufffd\ue8ec\ufffd\ufffd\u02bd\ufffd\ufffdhhmmss<br>
	 * C type : TThostFtdcTradeTimeType
	 */
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > TradeTime() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02ee\ufffd\u0163\ufffdN/A<br>
	 * C type : TThostFtdcTradeSerialType
	 */
	@Array({9}) 
	@Field(4) 
	public Pointer<Byte > TradeSerial() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\u02fe\ufffd\ufffd\ufffd\ub8ec\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcFutureIDType
	 */
	@Array({11}) 
	@Field(5) 
	public Pointer<Byte > FutureID() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0434\ufffd\ufffd\ub8ec\ufffd\ufffd\u0772\ufffd\u046f\ufffd\ufffd\ufffd\u0435\u00f5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBankIDType
	 */
	@Array({4}) 
	@Field(6) 
	public Pointer<Byte > BankID() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0437\ufffd\ufffd\ufffd\ufffd\u0134\ufffd\ufffd\ub8ec\ufffd\ufffd\u0772\ufffd\u046f\ufffd\ufffd\ufffd\u0435\u00f5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	@Array({5}) 
	@Field(7) 
	public Pointer<Byte > BankBrchID() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u0531\ufffd\ufffdN/A<br>
	 * C type : TThostFtdcOperNoType
	 */
	@Array({17}) 
	@Field(8) 
	public Pointer<Byte > OperNo() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u8c78\ufffd\ufffd\ufffd\u0363\ufffdN/A<br>
	 * C type : TThostFtdcDeviceIDType
	 */
	@Array({3}) 
	@Field(9) 
	public Pointer<Byte > DeviceID() {
		return this.io.getPointerField(this, 9);
	}
	/**
	 * \ufffd\ufffd\u00bc\ufffd\ufffdN/A<br>
	 * C type : TThostFtdcRecordNumType
	 */
	@Array({7}) 
	@Field(10) 
	public Pointer<Byte > RecordNum() {
		return this.io.getPointerField(this, 10);
	}
	/**
	 * \ufffd\u1ef0\ufffd\ufffd\u0163\ufffdN/A<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(11) 
	public int SessionID() {
		return this.io.getIntField(this, 11);
	}
	/**
	 * \ufffd\u1ef0\ufffd\ufffd\u0163\ufffdN/A<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(11) 
	public CThostFtdcTransferHeaderField SessionID(int SessionID) {
		this.io.setIntField(this, 11, SessionID);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u0163\ufffdN/A<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(12) 
	public int RequestID() {
		return this.io.getIntField(this, 12);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u0163\ufffdN/A<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(12) 
	public CThostFtdcTransferHeaderField RequestID(int RequestID) {
		this.io.setIntField(this, 12, RequestID);
		return this;
	}
	public CThostFtdcTransferHeaderField() {
		super();
	}
	public CThostFtdcTransferHeaderField(Pointer pointer) {
		super(pointer);
	}
}
