package thosttraderapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\u05b9\ufffd\u036c\ufffd\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd\u032c\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : ctpapi/linux/ThostFtdcUserApiStruct.h:3744</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("thosttraderapi") 
public class CThostFtdcManualSyncBrokerUserOTPField extends StructObject {
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\u032c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcOTPTypeType
	 */
	@Field(2) 
	public byte OTPType() {
		return this.io.getByteField(this, 2);
	}
	/**
	 * \ufffd\ufffd\u032c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcOTPTypeType
	 */
	@Field(2) 
	public CThostFtdcManualSyncBrokerUserOTPField OTPType(byte OTPType) {
		this.io.setByteField(this, 2, OTPType);
		return this;
	}
	/**
	 * \ufffd\ufffd\u04bb\ufffd\ufffd\ufffd\ufffd\u032c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({41}) 
	@Field(3) 
	public Pointer<Byte > FirstOTP() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\u06b6\ufffd\ufffd\ufffd\ufffd\ufffd\u032c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({41}) 
	@Field(4) 
	public Pointer<Byte > SecondOTP() {
		return this.io.getPointerField(this, 4);
	}
	public CThostFtdcManualSyncBrokerUserOTPField() {
		super();
	}
	public CThostFtdcManualSyncBrokerUserOTPField(Pointer pointer) {
		super(pointer);
	}
}
