package thosttraderapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd\u0228\ufffd\ufffd<br>
 * <i>native declaration : ctpapi/linux/ThostFtdcUserApiStruct.h:510</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("thosttraderapi") 
public class CThostFtdcSuperUserFunctionField extends StructObject {
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(0) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0734\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcFunctionCodeType
	 */
	@Field(1) 
	public byte FunctionCode() {
		return this.io.getByteField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0734\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcFunctionCodeType
	 */
	@Field(1) 
	public CThostFtdcSuperUserFunctionField FunctionCode(byte FunctionCode) {
		this.io.setByteField(this, 1, FunctionCode);
		return this;
	}
	public CThostFtdcSuperUserFunctionField() {
		super();
	}
	public CThostFtdcSuperUserFunctionField(Pointer pointer) {
		super(pointer);
	}
}
