package thosttraderapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\u03fd\ufffd\ufffd\u05fa\ufffd\u053c\ufffd\u0135\ufffd\ufffd\ufffd<br>
 * <i>native declaration : ctpapi/linux/ThostFtdcUserApiStruct.h:2868</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("thosttraderapi") 
public class CThostFtdcCombinationLegField extends StructObject {
	/**
	 * \ufffd\ufffd\u03fa\ufffd\u053c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({31}) 
	@Field(0) 
	public Pointer<Byte > CombInstrumentID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0231\ufffd\ufffd<br>
	 * C type : TThostFtdcLegIDType
	 */
	@Field(1) 
	public int LegID() {
		return this.io.getIntField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0231\ufffd\ufffd<br>
	 * C type : TThostFtdcLegIDType
	 */
	@Field(1) 
	public CThostFtdcCombinationLegField LegID(int LegID) {
		this.io.setIntField(this, 1, LegID);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u023a\ufffd\u053c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({31}) 
	@Field(2) 
	public Pointer<Byte > LegInstrumentID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(3) 
	public byte Direction() {
		return this.io.getByteField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(3) 
	public CThostFtdcCombinationLegField Direction(byte Direction) {
		this.io.setByteField(this, 3, Direction);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u0233\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcLegMultipleType
	 */
	@Field(4) 
	public int LegMultiple() {
		return this.io.getIntField(this, 4);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0233\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcLegMultipleType
	 */
	@Field(4) 
	public CThostFtdcCombinationLegField LegMultiple(int LegMultiple) {
		this.io.setIntField(this, 4, LegMultiple);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcImplyLevelType
	 */
	@Field(5) 
	public int ImplyLevel() {
		return this.io.getIntField(this, 5);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcImplyLevelType
	 */
	@Field(5) 
	public CThostFtdcCombinationLegField ImplyLevel(int ImplyLevel) {
		this.io.setIntField(this, 5, ImplyLevel);
		return this;
	}
	public CThostFtdcCombinationLegField() {
		super();
	}
	public CThostFtdcCombinationLegField(Pointer pointer) {
		super(pointer);
	}
}
