package thosttraderapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\u037b\ufffd\u0368\u05aa<br>
 * <i>native declaration : ctpapi/linux/ThostFtdcUserApiStruct.h:2765</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("thosttraderapi") 
public class CThostFtdcNoticeField extends StructObject {
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\u03e2\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcContentType
	 */
	@Array({501}) 
	@Field(1) 
	public Pointer<Byte > Content() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\u0368\u05aa\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u043a\ufffd<br>
	 * C type : TThostFtdcSequenceLabelType
	 */
	@Array({2}) 
	@Field(2) 
	public Pointer<Byte > SequenceLabel() {
		return this.io.getPointerField(this, 2);
	}
	public CThostFtdcNoticeField() {
		super();
	}
	public CThostFtdcNoticeField(Pointer pointer) {
		super(pointer);
	}
}
