package thostmduserapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffdTradeCode=202001<br>
 * <i>native declaration : ctpapi/linux/ThostFtdcUserApiStruct.h:160</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("thostmduserapi") 
public class CThostFtdcTransferBankToFutureReqField extends StructObject {
	/**
	 * \ufffd\u06bb\ufffd\ufffd\u02bd\ufffd\ufffd\u02fb\ufffd<br>
	 * C type : TThostFtdcAccountIDType
	 */
	@Array({13}) 
	@Field(0) 
	public Pointer<Byte > FutureAccount() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcFuturePwdFlagType
	 */
	@Field(1) 
	public byte FuturePwdFlag() {
		return this.io.getByteField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcFuturePwdFlagType
	 */
	@Field(1) 
	public CThostFtdcTransferBankToFutureReqField FuturePwdFlag(byte FuturePwdFlag) {
		this.io.setByteField(this, 1, FuturePwdFlag);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcFutureAccPwdType
	 */
	@Array({17}) 
	@Field(2) 
	public Pointer<Byte > FutureAccPwd() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u05ea\ufffd\u02fd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(3) 
	public double TradeAmt() {
		return this.io.getDoubleField(this, 3);
	}
	/**
	 * \u05ea\ufffd\u02fd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(3) 
	public CThostFtdcTransferBankToFutureReqField TradeAmt(double TradeAmt) {
		this.io.setDoubleField(this, 3, TradeAmt);
		return this;
	}
	/**
	 * \ufffd\u037b\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(4) 
	public double CustFee() {
		return this.io.getDoubleField(this, 4);
	}
	/**
	 * \ufffd\u037b\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(4) 
	public CThostFtdcTransferBankToFutureReqField CustFee(double CustFee) {
		this.io.setDoubleField(this, 4, CustFee);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u05a3\ufffdRMB-\ufffd\ufffd\ufffd\ufffd\ufffd USD-\ufffd\ufffd\u0532 HKD-\ufffd\ufffd\u052a<br>
	 * C type : TThostFtdcCurrencyCodeType
	 */
	@Array({4}) 
	@Field(5) 
	public Pointer<Byte > CurrencyCode() {
		return this.io.getPointerField(this, 5);
	}
	public CThostFtdcTransferBankToFutureReqField() {
		super();
	}
	public CThostFtdcTransferBankToFutureReqField(Pointer pointer) {
		super(pointer);
	}
}
