package thostmduserapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\u00fb\ufffd\ufffd\u00bc\ufffd\u0368\u05aa\ufffd\ufffd\u03e2<br>
 * <i>native declaration : ctpapi/linux/ThostFtdcUserApiStruct.h:3240</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("thostmduserapi") 
public class CThostFtdcTradingNoticeInfoField extends StructObject {
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(2) 
	public Pointer<Byte > SendTime() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\u03e2\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcContentType
	 */
	@Array({501}) 
	@Field(3) 
	public Pointer<Byte > FieldContent() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u03f5\ufffd\u043a\ufffd<br>
	 * C type : TThostFtdcSequenceSeriesType
	 */
	@Field(4) 
	public short SequenceSeries() {
		return this.io.getShortField(this, 4);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u03f5\ufffd\u043a\ufffd<br>
	 * C type : TThostFtdcSequenceSeriesType
	 */
	@Field(4) 
	public CThostFtdcTradingNoticeInfoField SequenceSeries(short SequenceSeries) {
		this.io.setShortField(this, 4, SequenceSeries);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u043a\ufffd<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(5) 
	public int SequenceNo() {
		return this.io.getIntField(this, 5);
	}
	/**
	 * \ufffd\ufffd\ufffd\u043a\ufffd<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(5) 
	public CThostFtdcTradingNoticeInfoField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 5, SequenceNo);
		return this;
	}
	public CThostFtdcTradingNoticeInfoField() {
		super();
	}
	public CThostFtdcTradingNoticeInfoField(Pointer pointer) {
		super(pointer);
	}
}
