package thostmduserapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\u00fb\ufffd\ufffd\u00bc\ufffd\u0368\u05aa<br>
 * <i>native declaration : ctpapi/linux/ThostFtdcUserApiStruct.h:3257</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("thostmduserapi") 
public class CThostFtdcTradingNoticeField extends StructObject {
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f7\ufffd\u03a7<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1) 
	public byte InvestorRange() {
		return this.io.getByteField(this, 1);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f7\ufffd\u03a7<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1) 
	public CThostFtdcTradingNoticeField InvestorRange(byte InvestorRange) {
		this.io.setByteField(this, 1, InvestorRange);
		return this;
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({13}) 
	@Field(2) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u03f5\ufffd\u043a\ufffd<br>
	 * C type : TThostFtdcSequenceSeriesType
	 */
	@Field(3) 
	public short SequenceSeries() {
		return this.io.getShortField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u03f5\ufffd\u043a\ufffd<br>
	 * C type : TThostFtdcSequenceSeriesType
	 */
	@Field(3) 
	public CThostFtdcTradingNoticeField SequenceSeries(short SequenceSeries) {
		this.io.setShortField(this, 3, SequenceSeries);
		return this;
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(4) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(5) 
	public Pointer<Byte > SendTime() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \ufffd\ufffd\ufffd\u043a\ufffd<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(6) 
	public int SequenceNo() {
		return this.io.getIntField(this, 6);
	}
	/**
	 * \ufffd\ufffd\ufffd\u043a\ufffd<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(6) 
	public CThostFtdcTradingNoticeField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 6, SequenceNo);
		return this;
	}
	/**
	 * \ufffd\ufffd\u03e2\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcContentType
	 */
	@Array({501}) 
	@Field(7) 
	public Pointer<Byte > FieldContent() {
		return this.io.getPointerField(this, 7);
	}
	public CThostFtdcTradingNoticeField() {
		super();
	}
	public CThostFtdcTradingNoticeField(Pointer pointer) {
		super(pointer);
	}
}
